server:
  port: 8082
  tomcat:
      uri-encoding: utf-8

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  security:
    user:
      name: root
      password: root
  kafka:
      consumer:
        enable-auto-commit: true
        group-id: bigdata
        auto-offset-reset: latest
        bootstrap-servers: localhost:9092
      producer:
        bootstrap-servers: localhost:9092
        retries: 3
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
#        max:
#          request:
#              size : 1024

  data:
    neo4j:
      uri: bolt://192.168.1.120:7687
      username: neo4j
      password: root
    mongodb:
      host: localhost
      port: 27017
      database: test
  jta:
    narayana:
      log-dir:

mybatis:
  config-location: classpath:mybatis.xml
#  configuration:
#      log-impl:   org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.example.bigdata.common.type
#
#logging:
#  level: debug




